### ISSUE TITLE
for metin2

### ISSUE THREAD

**Issue by Muhtar0** [hatz2/GflessClient#12]
Hello, first of all, thank you for the code.
Should I use a separate blackbox for each account?
How do I update the certificate?
I edited the code for Metin2 and logged into the game without any issues. However, now when I try to login the account through GFLess, it gives an invalid login credentials (wrong ID or password) error. I also get the same error when trying to log in through Gameforge. What do you suggest as a solution?
How can I find the request information?
Can I create my own blackbox generator?

**Comment by hatz2** [comment]
@Muhtar0 

Q: Should I use a separate blackbox for each account?
A: If you want to be safe then yes but I don't think the specific game team have access to that information anyways.

Q: How do I update the certificate?
A: The current certificate is valid so you don't really need to update it but in case you are interested into doing that then you'd need to debug the gameforge client, find where the certificate is getting loaded from disk and then extract it.

Q: I edited the code for Metin2 and logged into the game without any issues. However, now when I try to login the account through GFLess, it gives an invalid login credentials (wrong ID or password) error. I also get the same error when trying to log in through Gameforge. What do you suggest as a solution?
A: If the gamefoge client is also rejecting your login requests then there's no way to fix that through the Gfless Client because it just mimics what the gfclient does.

Q: How can I find the request information?
A: Using an http debugger like Fiddler or HTTP Debugger Pro.

Q: Can I create my own blackbox generator?
A: I don't know why would you want to create your own blackbox generator since it is already implemented in Gfless Client.
